version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.13.3-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
  web:
    build: .
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 80
    volumes:
      - ../
    ports:
      - 8000:8000
    depends_on:
      - db 
  db:
    image: postgres:14
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      