from django.urls import path
from matrix import views

urlpatterns = [
    path('mine/',
         views.ManageMatrixListView.as_view(),
         name='manage_matrix_list'),
    path('create/',
         views.MatrixCreateView.as_view(),
         name='matrix_create'),
    path('<pk>/edit/',
         views.MatrixUpdateView.as_view(),
         name='matrix_edit'),
    path('<pk>/delete/',
         views.MatrixDeleteView.as_view(),
         name='matrix_delete'),
    path('<pk>/module/',
         views.MatrixBlockUpdateView.as_view(),
         name='matrix_block_update'),
    path('block/<int:block_id>/content/<model_name>/create/',
         views.ContentCreateUpdateView.as_view(),
         name='block_content_create'),
    path('block/<int:module_id>/content/<model_name>/<id>/',
         views.ContentCreateUpdateView.as_view(),
         name='block_content_update'),
    path('content/<int:id>/delete/',
         views.ContentDeleteView.as_view(),
         name='block_content_delete'),
    path('module/<int:module_id>/',
         views.BlockContentListView.as_view(),
         name='block_content_list'),
    path('module/order/',
         views.BlockOrderView.as_view(),
         name='block_order'),
    path('content/order/',
         views.ContentOrderView.as_view(),
         name='content_order'),

    path('subject/<slug:subject>/',
         views.MatrixListView.as_view(),
         name='matrix_list_subject'),
    path('<slug:slug>/',
         views.MatrixDetailView.as_view(),
         name='matrix_detail'),
]
