# Generated by Django 5.0.3 on 2024-03-27 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("owner", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MLAlgo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=128)),
                ("code", models.CharField(max_length=50000)),
                ("version", models.CharField(max_length=128)),
                ("owner", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="endpoints.endpoint",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MLAlgoStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=128)),
                ("active", models.BooleanField()),
                ("created_by", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_mlalgo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status",
                        to="endpoints.mlalgo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MLRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.CharField(max_length=10000)),
                ("full_response", models.CharField(max_length=10000)),
                ("response", models.CharField(max_length=10000)),
                ("feedback", models.CharField(blank=True, max_length=10000, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_mlalgo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="endpoints.mlalgo",
                    ),
                ),
            ],
        ),
    ]
