# Generated by Django 5.0.3 on 2024-03-29 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endpoints", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ABTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=10000)),
                ("created_by", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.CharField(blank=True, max_length=10000, null=True)),
                (
                    "parent_mlalgo_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_mlalgo_1",
                        to="endpoints.mlalgo",
                    ),
                ),
                (
                    "parent_mlalgo_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_mlalgo_2",
                        to="endpoints.mlalgo",
                    ),
                ),
            ],
        ),
    ]
