version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod 
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; poetry run gunicorn --bind 0.0.0.0:8000 config.wsgi'
    ports:
      - 8008:8000
    environment:
      - DEBUG=0
      - DATABASE_URL=postgresql://django_start:django_start@db:5432/django_start
    depends_on:
      - db 
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=django_start
      - POSTGRES_PASSWORD=django_start
      - POSTGRES_DB=django_start

volumes:
  postgres_data_prod: