[tool.poetry]
name = "app-04"
version = "0.1.0"
description = "App with fastapi"
authors = ["golanghack <golanghack@gmail.com>"]
license = "BSD"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
