# Generated by Django 5.0.6 on 2024-06-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="file name", max_length=200, verbose_name="file name"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="file", upload_to="", verbose_name="file"
                    ),
                ),
            ],
        ),
    ]
