# Generated by Django 5.1 on 2024-08-07 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fdc_id", models.IntegerField()),
                ("description", models.CharField(max_length=255)),
                ("food_category", models.IntegerField()),
                ("energy_value", models.FloatField()),
                ("fat_value", models.FloatField()),
                ("protein_value", models.FloatField()),
                ("carbohydrate_value", models.FloatField()),
                ("fuel_category", models.CharField(max_length=50)),
                ("user_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MealTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meal_time", models.CharField(max_length=50)),
                ("portion_size", models.FloatField()),
                ("date", models.DateField()),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="statistic.fooditem",
                    ),
                ),
            ],
        ),
    ]
