version: '3.8'
services:
  redis:
    image: redis:3.2.8
    hostname: redis
    restart: always
    ports:
      - 5672:5672
  rabbitmq:
    image: rabbitmq:3.13.3-management
    hostname: rabbitmq
    restart: always
    environment:      
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
  service_1:
    build: 
      context: ./app/service_1
      dockerfile: Dockerfile 
  service_2:    
    build:
      context: ./app/service_2
      dockerfile: Dockerfile

  web:
    build: .
    command: poetry run app/./manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"    